apiVersion: argoproj.io/v1alpha1co
kind: Applications
metadata:
  name: harnessApp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xrlim97/harnesscd-example-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: harnessApp
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true