pipeline:
  name: shantelleGit
  identifier: shantelleGit
  projectIdentifier: Shantelle_Project
  orgIdentifier: UX_Team
  tags: {}
  stages:
    - stage:
        name: Custo
        identifier: Custo
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
    - stage:
        name: kubernetes
        identifier: kubernetes
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sample_service_1678068340991
          environment:
            environmentRef: dev_1678067453867
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster_1678067453867
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 12s
                  spec:
                    skipDryRun: ""
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: sapmple
      type: String
      description: ""
      required: false
      value: <+input>
