pipeline:
  name: shantelleGit
  identifier: shantelleGit
  projectIdentifier: Shantelle_Project
  orgIdentifier: UX_Team
  tags: {}
  stages:
    - stage:
        name: Custo
        identifier: Custo
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
  variables:
    - name: sapmple
      type: String
      description: ""
      required: false
      value: <+input>
